config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :zombies
  get 'home/index'
  root 'home#index'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :zombies	 
end

app/models/zombie.rb
class Zombie < ApplicationRecord
belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_zombie, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)
    @zombie.user = current_user
    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render :show, status: :created, location: @zombie }
      else
        format.html { render :new }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { render :show, status: :ok, location: @zombie }
      else
        format.html { render :edit }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url, notice: 'Zombie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zombie
      @zombie = Zombie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:killed, :name, :health, :photo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/home/index.html.erb
<div class="card bg-dark text-white">
  <img src="http://assets.rebelcircus.com/blog/wp-content/uploads/2016/09/8d1554d0-66b1-4bec-aa8f-810679e00131_zps02f0d308.jpg" class="card-img img-responsive" alt="...">
  <div class="card-img-overlay">
    <h2 class="card-title">ZOMBIE FACTORY</h2>
    <p class="card-text">The zombie, often portrayed as an undead, flesh-eating, decaying corpse, has enjoyed a popularity surge in recent years. Whether they’re devouring their prey in The Walking Dead or getting their groove on in Michael Jackson’s “Thriller” video, zombies dominate pop culture. But are zombies real? Unlike many other monsters—which are mostly a product of superstition, religion and fear— zombies have a basis in fact, and several verified cases of zombies have been reported from Haitian voodoo culture.</p>
	
	<p>Zombie Traits</p>

	<p>A zombie, according to pop culture and folklore, is usually either a reawakened corpse with a ravenous appetite or someone bitten by another zombie infected with a “zombie virus.”

	Zombies are usually portrayed as strong but robotic beings with rotting flesh. Their only mission is to feed. They typically don’t have conversations (although some may grunt a little).</p>

	<p>Origin of Zombies</p>

	<p>The Ancient Greeks may have been the first civilization terrorized by a fear of the undead. Archaeologists have unearthed many ancient graves which contained skeletons pinned down by rocks and other heavy objects, assumedly to prevent the dead bodies from reanimating.

	Zombie folklore has been around for centuries in Haiti, possibly originating in the 17th century when West African slaves were brought in to work on Haiti’s sugar cane plantations. Brutal conditions left the slaves longing for freedom. According to some reports, the life—or rather afterlife—of a zombie represented the horrific plight of slavery.</p>
	<br>
    <br>
    <br>
    <br>



        <img src="https://media.giphy.com/media/Z4IXspU3iCHlK/giphy.gif" class="img-responsive rounded mx-auto d-block" alt="Triller"/>
        
    
    <br>
    <br>
    <br>
    <br>

    <p class="card-text">To be continued...</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Zombies Attack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
            <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
            <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

</div>
    <%= yield %>
  </body>
</html>

app/views/shared/_navbar.html.erb
    <div class="pos-f-t">
  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-4">
      <h5 class="text-white h4">HEROKU APP</h5>
      <span class="text-muted">Zombie Generator</span>
      
    </div>
  </div>
  <nav class="navbar navbar-light bg-light"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to 'Zombies', zombies_path, method: :get, class:"btn btn-secondary" %>
  
    <% if user_signed_in? %>
      <li>Welcome  <%= current_user.email %></li>
      <li><%= link_to "modificar datos", edit_user_registration_path, method: :get %></li>
      <li><%= link_to "cancelar cuenta", cancel_user_registration_path, method: :get %></li>
      <li><%= link_to "cerrar sesion", destroy_user_session_path, method: :delete %></li>
      <% else %>
      <li class="text-white"><%= link_to "iniciar sesion",  new_user_session_path, method: :get %></li>
    <%end%>
    
  </nav>

app/views/zombies/_form.html.erb
<%= form_with(model: zombie, local: true) do |form| %>
  <% if zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% zombie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :killed %>
    <%= form.number_field :killed %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :health %>
    <%= form.number_field :health %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.text_field :photo %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing Zombie</h1>

<%= render 'form', zombie: @zombie %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1> - Zombies Members - </h1>
  <H3><%= link_to 'New Zombie', new_zombie_path %></H3>

    <div class="row">
    
      <% @zombies.each do |zombie| %>
      <div class="card m-5" style="width: 18rem;">    
              <%= image_tag zombie.photo, alt:"Zombie Picture", class:'img-responsive img-thumbnail' %>
              <H5>Kill  <%= zombie.killed %></H5>
              <H5>Name  <%= zombie.name %></H5>
              <H5>Healt <%= zombie.health %></H5>
              <p>Owner:   <%= zombie.user.try(:email)%></p>
              <div class="container"> 
                  <%= link_to 'Show', zombie, class: "btn btn-primary" %>
                  <%= link_to 'Edit', edit_zombie_path(zombie), class: "btn btn-secondary" %>
                  <%= link_to 'Destroy', zombie, method: :delete, data: {confirm: 'Are you 
                    sure?' }, class: "btn btn-danger" %>
                  
              </div>
      </div> 
    <% end %>

    </div>
    
        
    

app/views/zombies/new.html.erb
<h1>New Zombie</h1>



<%= render 'form', zombie: @zombie %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Killed:</strong>
  <%= @zombie.killed %>
</p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Health:</strong>
  <%= @zombie.health %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @zombie.photo %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>